# Generated by Django 3.2 on 2023-03-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('business_name', models.CharField(max_length=100, unique=True)),
                ('business_address', models.TextField(null=True)),
                ('business_lga', models.CharField(choices=[('Agege', 'Agege'), ('Ajeromi-Ifelodun', 'Ajeromi-Ifelodun'), ('Alimosho', 'Alimosho'), ('Apapa', 'Apapa'), ('Amuwo-Odofin', 'Amuwo-Odofin'), ('Badagry', 'Badagry'), ('Epe', 'Epe'), ('Eti-Osa', 'Eti-Osa'), ('Ibeju-Lekki', 'Ibeju-Lekki'), ('Ifako-Ijaiye', 'Ifako-Ijaiye'), ('Ikeja', 'Ikeja'), ('Ikorodu', 'Ikorodu'), ('Kosofe', 'Kosofe'), ('Lagos Island', 'Lagos Island'), ('Lagos Mainland', 'Lagos Mainland'), ('Mushin', 'Mushin'), ('Ojo', 'Ojo'), ('Oshodi-Isolo', 'Oshodi-Isolo'), ('Somolu', 'Somolu'), ('Surulere', 'Surulere')], max_length=60)),
                ('business_state', models.CharField(max_length=100, null=True)),
                ('business_phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('image', models.CharField(max_length=200)),
                ('first_reference', models.CharField(max_length=30)),
                ('second_reference', models.CharField(max_length=30)),
                ('is_online', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-business_lga',),
            },
        ),
    ]
