# Generated by Django 3.2 on 2023-04-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailers', '0003_rename_retailer_retailers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailers',
            name='business_phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
