# Generated by Django 4.1.7 on 2023-06-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retailers", "0004_alter_retailers_business_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="retailers",
            name="lga_code",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="retailers",
            name="state_code",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
