# Generated by Django 4.1.7 on 2023-06-06 14:48

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("retailers", "0006_alter_retailers_options_staff_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staff",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 6, 6, 14, 48, 34, 294735, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
