# Generated by Django 4.1.7 on 2023-06-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "retailers",
            "0008_remove_retailers_email_remove_retailers_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="retailers",
            name="business_lga",
            field=models.CharField(
                choices=[
                    ["Agege", "Agege"],
                    ["Ajeromi-Ifelodun", "Ajeromi-Ifelodun"],
                    ["Alimosho", "Alimosho"],
                    ["Apapa", "Apapa"],
                    ["Amuwo-Odofin", "Amuwo-Odofin"],
                    ["Badagry", "Badagry"],
                    ["Epe", "Epe"],
                    ["Eti-Osa", "Eti-Osa"],
                    ["Ibeju-Lekki", "Ibeju-Lekki"],
                    ["Ifako-Ijaiye", "Ifako-Ijaiye"],
                    ["Ikeja", "Ikeja"],
                    ["Ikorodu", "Ikorodu"],
                    ["Kosofe", "Kosofe"],
                    ["Lagos Island", "Lagos Island"],
                    ["Lagos Mainland", "Lagos Mainland"],
                    ["Mushin", "Mushin"],
                    ["Ojo", "Ojo"],
                    ["Oshodi-Isolo", "Oshodi-Isolo"],
                    ["Somolu", "Somolu"],
                    ["Surulere", "Surulere"],
                ],
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="retailers",
            name="business_state",
            field=models.CharField(
                choices=[
                    ["AB", "Abia"],
                    ["AD", "Adamawa"],
                    ["AK", "Akwa Ibom"],
                    ["AN", "Anambra"],
                    ["BA", "Bauchi"],
                    ["BY", "Bayelsa"],
                    ["BE", "Benue"],
                    ["BO", "Borno"],
                    ["CR", "Cross River"],
                    ["DE", "Delta"],
                    ["EB", "Ebonyi"],
                    ["ED", "Edo"],
                    ["EK", "Ekiti"],
                    ["EN", "Enugu"],
                    ["GO", "Gombe"],
                    ["IM", "Imo"],
                    ["JI", "Jigawa"],
                    ["KA", "Kaduna"],
                    ["KN", "Kano"],
                    ["KT", "Katsina"],
                    ["KE", "Kebbi"],
                    ["KO", "Kogi"],
                    ["KW", "Kwara"],
                    ["LG", "Lagos"],
                    ["NA", "Nasarawa"],
                    ["NI", "Niger"],
                    ["OG", "Ogun"],
                    ["ON", "Ondo"],
                    ["OS", "Osun"],
                    ["OY", "Oyo"],
                    ["PL", "Plateau"],
                    ["RI", "Rivers"],
                    ["SO", "Sokoto"],
                    ["TA", "Taraba"],
                    ["YO", "Yobe"],
                    ["ZA", "Zamfara"],
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
