# Generated by Django 4.1.7 on 2023-06-07 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retailers", "0009_alter_retailers_business_lga_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="manager_code",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 6, 7, 14, 57, 8, 683574, tzinfo=datetime.timezone.utc
                ),
                max_length=8,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
