# Generated by Django 4.1.7 on 2023-06-07 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retailers", "0012_remove_manager_dob_remove_staff_dob_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="dob",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 6, 7, 16, 1, 7, 535720, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
