# Generated by Django 4.1.7 on 2023-06-07 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("retailers", "0014_alter_manager_mobile_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manager",
            name="mobile_number",
        ),
    ]
