# Generated by Django 4.1.7 on 2023-06-06 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("retailers", "0006_alter_retailers_options_staff_manager"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryOfficer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_code", models.CharField(max_length=8, unique=True)),
                ("first_name", models.CharField(max_length=60)),
                ("last_name", models.CharField(max_length=60)),
                ("gender", models.CharField(max_length=10)),
                ("dob", models.DateField()),
                (
                    "ro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_officers",
                        to="retailers.retailers",
                    ),
                ),
            ],
        ),
    ]
