# Generated by Django 4.1.7 on 2023-06-21 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0002_alter_deliveryofficer_ro"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deliveryofficer",
            old_name="ro",
            new_name="manager",
        ),
    ]
