# Generated by Django 4.1.7 on 2023-06-21 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0004_alter_deliveryofficer_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryofficer",
            name="nok_first_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="deliveryofficer",
            name="nok_last_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="deliveryofficer",
            name="nok_phone_number",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="must be a valid phone number", regex="^[0]\\d{10}$"
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="deliveryofficer",
            name="nok_relationship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Brother", "Brother"),
                    ("Sister", "Sister"),
                    ("Father", "Father"),
                    ("Mother", "Mother"),
                    ("Husband", "Husband"),
                    ("Wife", "Wife"),
                ],
                max_length=30,
            ),
        ),
    ]
