# Generated by Django 4.1.7 on 2023-06-21 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0005_deliveryofficer_nok_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryofficer",
            name="do_phone_number",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="must be a valid phone number", regex="^[0]\\d{10}$"
                    )
                ],
            ),
        ),
    ]
