# Generated by Django 4.1.7 on 2023-06-21 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0006_deliveryofficer_do_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliveryofficer",
            options={"ordering": ["-date_created"]},
        ),
        migrations.RemoveField(
            model_name="deliveryofficer",
            name="dob",
        ),
        migrations.AddField(
            model_name="deliveryofficer",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 6, 21, 13, 37, 54, 777516, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
