# Generated by Django 3.2 on 2023-03-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderOnboardBilling',
        ),
    ]
