# Generated by Django 3.2 on 2023-03-15 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0002_delete_orderonboardbilling'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderOnboardBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_sub', models.DecimalField(decimal_places=2, default=10000.0, max_digits=8)),
                ('cylinder_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('gas_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('biller', models.CharField(blank=True, default='Homefort Delivery Staff', max_length=50, null=True)),
                ('total_cost', models.CharField(blank=True, default='00.00', max_length=20, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_onboard_order', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarded_order', to='orders.onboardingorder')),
            ],
        ),
    ]
