# Generated by Django 3.2 on 2023-03-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_orderonboardbilling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderonboardbilling',
            name='gas_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=9600.0, max_digits=8, null=True),
        ),
    ]
