# Generated by Django 3.2 on 2023-03-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_orderonboardbilling_gas_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderonboardbilling',
            name='cylinder_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=18000.0, max_digits=8, null=True),
        ),
    ]
