# Generated by Django 3.2 on 2023-03-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_orderonboardbilling_cylinder_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderonboardbilling',
            name='total_cost',
            field=models.CharField(blank=True, default='00.00', editable=False, max_length=20, null=True),
        ),
    ]
