# Generated by Django 3.2 on 2023-03-16 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('billing', '0006_alter_orderonboardbilling_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderonboardbilling',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarded_order', to='orders.onboardingorder'),
        ),
    ]
