# Generated by Django 3.2 on 2023-04-17 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_orderonboardbilling_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderonboardbilling',
            old_name='cylinder_cost',
            new_name='cylinder_fee',
        ),
        migrations.RenameField(
            model_name='orderonboardbilling',
            old_name='gas_cost',
            new_name='gas_fee',
        ),
    ]
