# Generated by Django 4.1.7 on 2023-05-19 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_auto_20230417_0751"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderonboardbilling", options={"ordering": ["-date_created"]},
        ),
    ]
