# Generated by Django 3.2 on 2023-02-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cylinder',
            fields=[
                ('cylinder_type', models.CharField(blank=True, choices=[('please select', 'please select'), ('12kg', '12kg'), ('25kg', '25kg'), ('50kg', '50kg')], default='please select', max_length=20)),
                ('cylinder_serial_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cylinder_weight', models.FloatField()),
                ('cylinder_status', models.CharField(blank=True, default='unassigned', max_length=20)),
                ('manufacturer', models.CharField(default='Amaze Gas', max_length=30)),
                ('cylinder_tar_weight', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('manufacture_date', models.DateField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('maintenance_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SmartBox',
            fields=[
                ('box_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(default='Homefort Energy', max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmartScale',
            fields=[
                ('scale_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(default='Homefort Energy', max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
