# Generated by Django 3.2 on 2023-02-27 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0002_auto_20230227_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartBox',
            fields=[
                ('box_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(default='Homefort Energy', max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmartScale',
            fields=[
                ('scale_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(default='Homefort Energy', max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SmartDevice',
        ),
        migrations.RenameField(
            model_name='assigncylinder',
            old_name='date',
            new_name='date_assigned',
        ),
        migrations.AlterField(
            model_name='assigncylinder',
            name='cylinder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.cylinder'),
        ),
        migrations.AlterField(
            model_name='assigncylinder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_cylinder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assigncylinder',
            name='smart_box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.smartbox'),
        ),
        migrations.AlterField(
            model_name='assigncylinder',
            name='smart_scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.smartscale'),
        ),
    ]
