# Generated by Django 3.2 on 2023-03-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20230227_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='CylinderMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operations_staff', models.CharField(max_length=20)),
                ('operations_staff_name', models.CharField(max_length=50)),
                ('cylinder', models.CharField(max_length=30)),
                ('from_location', models.CharField(blank=True, max_length=30, null=True)),
                ('to_location', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('history_type', models.CharField(default='Regular', max_length=30)),
                ('cylinder_status', models.CharField(blank=True, max_length=30, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
