# Generated by Django 3.2 on 2023-03-08 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_cylindermovement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigncylinder',
            name='cylinder',
        ),
    ]
