# Generated by Django 3.2 on 2023-03-10 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20230308_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smartbox',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='smartbox',
            old_name='date_added',
            new_name='date_created',
        ),
    ]
