# Generated by Django 3.2 on 2023-03-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_auto_20230310_0711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cylinder',
            options={'ordering': ['-date_added']},
        ),
        migrations.AddField(
            model_name='smartbox',
            name='smartbox_status',
            field=models.CharField(blank=True, default='unassigned', max_length=20),
        ),
        migrations.AddField(
            model_name='smartscale',
            name='smartscale_status',
            field=models.CharField(blank=True, default='unassigned', max_length=20),
        ),
    ]
