# Generated by Django 3.2 on 2023-03-10 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0011_auto_20230310_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailAssignCylinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('cylinder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.cylinder')),
                ('smart_box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.smartbox')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='retail_assigned_cylinder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-assigned_date',),
            },
        ),
    ]
