# Generated by Django 3.2 on 2023-03-10 09:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0012_retailassigncylinder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssignCylinder',
            new_name='SMEAssignCylinder',
        ),
    ]
