# Generated by Django 4.1.7 on 2023-05-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0013_rename_assigncylinder_smeassigncylinder"),
    ]

    operations = [
        migrations.CreateModel(
            name="GasPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        decimal_places=2, default="0.00", max_digits=10, max_length=10
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OtherBillableAssets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "low_pressure_regulator_price",
                    models.DecimalField(
                        decimal_places=2, default="0.00kg", max_digits=10, max_length=10
                    ),
                ),
                (
                    "high_pressure_regulator_price",
                    models.DecimalField(
                        decimal_places=2, default="0.00kg", max_digits=10, max_length=10
                    ),
                ),
                (
                    "high_pressure_hose_price",
                    models.DecimalField(
                        decimal_places=2, default="0.00kg", max_digits=10, max_length=10
                    ),
                ),
                (
                    "low_pressure_hose_price",
                    models.DecimalField(
                        decimal_places=2, default="0.00kg", max_digits=10, max_length=10
                    ),
                ),
                (
                    "subsidized_cylinder_price",
                    models.DecimalField(
                        decimal_places=2, default="0.00kg", max_digits=10, max_length=10
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
