# Generated by Django 4.1.7 on 2023-05-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0014_gasprice_otherbillableassets"),
    ]

    operations = [
        migrations.AddField(
            model_name="gasprice",
            name="user",
            field=models.CharField(blank=True, default="Homefort Admin", max_length=30),
        ),
        migrations.AddField(
            model_name="otherbillableassets",
            name="user",
            field=models.CharField(blank=True, default="Homefort Admin", max_length=30),
        ),
    ]
