# Generated by Django 4.1.7 on 2023-05-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0015_gasprice_user_otherbillableassets_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="otherbillableassets",
            old_name="high_pressure_hose_price",
            new_name="high_pressure_hose_price_per_yard",
        ),
        migrations.RenameField(
            model_name="otherbillableassets",
            old_name="high_pressure_regulator_price",
            new_name="high_pressure_regulator_price_per_yard",
        ),
        migrations.RenameField(
            model_name="otherbillableassets",
            old_name="low_pressure_hose_price",
            new_name="low_pressure_hose_price_per_yard",
        ),
        migrations.RenameField(
            model_name="otherbillableassets",
            old_name="low_pressure_regulator_price",
            new_name="low_pressure_regulator_price_per_yard",
        ),
    ]
