# Generated by Django 4.1.7 on 2023-05-23 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "asset",
            "0016_rename_high_pressure_hose_price_otherbillableassets_high_pressure_hose_price_per_yard_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gasprice", options={"ordering": ("-date_added",)},
        ),
        migrations.AlterModelOptions(
            name="otherbillableassets", options={"ordering": ("-date_added",)},
        ),
    ]
