# Generated by Django 4.1.7 on 2023-05-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0017_alter_gasprice_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cylinder",
            old_name="cylinder_type",
            new_name="cylinder_capacity",
        ),
        migrations.RenameField(
            model_name="cylinder",
            old_name="cylinder_weight",
            new_name="cylinder_total_weight",
        ),
        migrations.RenameField(
            model_name="cylinder",
            old_name="manufacture_date",
            new_name="manufactured_date",
        ),
        migrations.AlterField(
            model_name="cylinder",
            name="manufacturer",
            field=models.CharField(default="Homefort Energy", max_length=30),
        ),
    ]
