# Generated by Django 4.1.7 on 2023-05-25 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0018_rename_cylinder_type_cylinder_cylinder_capacity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cylinder",
            name="current_actor",
            field=models.CharField(
                choices=[("DO", "DO"), ("RO", "RO"), ("HQ", "HQ")],
                default="HQ",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="cylinder",
            name="gas_content",
            field=models.CharField(blank=True, default=12.0, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="cylinder",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("storage", "storage"),
                    ("plant", "plant"),
                    ("maintenance_hub", "maintenance_hub"),
                    ("logistic_officer", "logistic_officer"),
                ],
                default="storage",
                max_length=20,
                null=True,
            ),
        ),
    ]
