# Generated by Django 4.1.7 on 2023-05-25 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0020_alter_cylinder_current_actor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cylinder",
            old_name="gas_content",
            new_name="cylinder_gas_content",
        ),
    ]
