# Generated by Django 4.1.7 on 2023-05-25 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0021_rename_gas_content_cylinder_cylinder_gas_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cylinder",
            old_name="cylinder_tar_weight",
            new_name="cylinder_tare_weight",
        ),
    ]
