# Generated by Django 4.1.7 on 2023-05-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0022_rename_cylinder_tar_weight_cylinder_cylinder_tare_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cylinder",
            name="cylinder_gas_content",
            field=models.DecimalField(
                decimal_places=2, default=12.0, max_digits=5, max_length=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cylinder",
            name="cylinder_tare_weight",
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=10),
        ),
    ]
