# Generated by Django 4.1.7 on 2023-05-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0023_alter_cylinder_cylinder_gas_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cylinder",
            name="cylinder_capacity",
            field=models.CharField(
                blank=True,
                choices=[("12kg", "12kg"), ("25kg", "25kg"), ("50kg", "50kg")],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="cylinder",
            name="cylinder_serial_number",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
