# Generated by Django 4.1.7 on 2023-05-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0024_alter_cylinder_cylinder_capacity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cylinder",
            name="expiry_status",
            field=models.BooleanField(default=False),
        ),
    ]
