# Generated by Django 4.1.7 on 2023-05-26 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0025_cylinder_expiry_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="cylinder",
            name="gas_content_type",
            field=models.CharField(
                choices=[("contentF", "contentF"), ("remnant", "remnant")],
                default="contentF",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="cylinder",
            name="cylinder_gas_content",
            field=models.DecimalField(
                decimal_places=2, default=12.0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cylinder",
            name="cylinder_tare_weight",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="cylinder",
            name="cylinder_total_weight",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
