# Generated by Django 4.1.7 on 2023-05-29 07:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meter_readings", "0012_alter_activatedsmartboxreading_smart_box"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("asset", "0026_cylinder_gas_content_type_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RetailAssignCylinder",
            new_name="ResidentialAssignCylinder",
        ),
    ]
