# Generated by Django 3.2 on 2023-02-25 12:02

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public identifier')),
                ('business_name', models.CharField(default='Homefort SME', max_length=100)),
                ('business_address', models.CharField(default='1, Faneye Street, Alagomeji, Yaba', max_length=100)),
                ('business_state', models.CharField(default='Lagos', max_length=20)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='must be a valid phone number', regex='^[0]\\d{10}$')])),
                ('image', models.CharField(blank=True, max_length=300, null=True)),
                ('business_type', models.CharField(blank=True, max_length=30, null=True)),
                ('has_new_shop', models.CharField(blank=True, max_length=30, null=True)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Client'), (2, 'Admin'), (3, 'Delivery'), (4, 'Ops')], default=1, null=True)),
                ('asset_type', models.CharField(blank=True, max_length=30, null=True)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('has_cylinder', models.CharField(blank=True, max_length=30, null=True)),
                ('cylinder_size', models.CharField(blank=True, max_length=30, null=True)),
                ('cylinder_position', models.CharField(blank=True, max_length=30, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bvn', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
