# Generated by Django 3.2 on 2023-02-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_bvn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, default='Homefort SME', max_length=100),
        ),
    ]
