# Generated by Django 3.2 on 2023-03-08 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_business_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMEUser',
            fields=[
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sme_users', serialize=False, to='accounts.user')),
                ('business_name', models.CharField(blank=True, default='Homefort SME', max_length=100)),
                ('business_address', models.CharField(default='1, Faneye Street, Alagomeji, Yaba', max_length=100)),
                ('business_state', models.CharField(default='Lagos', max_length=20)),
                ('business_type', models.CharField(blank=True, max_length=30, null=True)),
                ('has_new_shop', models.CharField(blank=True, max_length=30, null=True)),
                ('asset_type', models.CharField(blank=True, max_length=30, null=True)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('has_cylinder', models.CharField(blank=True, max_length=30, null=True)),
                ('cylinder_size', models.CharField(blank=True, max_length=30, null=True)),
                ('cylinder_position', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-date_joined',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='business_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cylinder_position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cylinder_size',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_cylinder',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_new_shop',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lga',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Sme'), (2, 'Admin'), (3, 'Delivery'), (4, 'Ops'), (5, 'Client')], default=1, null=True),
        ),
    ]
