# Generated by Django 3.2 on 2023-03-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230308_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.CharField(blank=True, default='Retail Clients', max_length=30, null=True),
        ),
    ]
