# Generated by Django 3.2 on 2023-03-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_business_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smeuser',
            options={'ordering': ('-date_joined',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Sme'), (2, 'Admin'), (3, 'Delivery'), (4, 'Ops'), (5, 'Client')], default=5, null=True),
        ),
    ]
