# Generated by Django 3.2 on 2023-03-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230308_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='smeuser',
            name='business_lga',
            field=models.CharField(default='Yaba', max_length=20),
        ),
        migrations.AddField(
            model_name='smeuser',
            name='which_user',
            field=models.CharField(blank=True, default='new_user', max_length=100, null=True),
        ),
    ]
