# Generated by Django 3.2 on 2023-03-08 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230308_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='smeuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='must be a valid phone number', regex='^[0]\\d{10}$')]),
        ),
    ]
