# Generated by Django 3.2 on 2023-03-08 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_smeuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMEUser2',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.user')),
                ('which_user', models.CharField(blank=True, default='sme_new_user', max_length=100, null=True)),
                ('business_name', models.CharField(blank=True, default='Homefort SME', max_length=100)),
                ('business_address', models.CharField(default='1, Faneye Street, Alagomeji, Yaba', max_length=100)),
                ('business_lga', models.CharField(default='Yaba', max_length=20)),
                ('business_state', models.CharField(default='Lagos', max_length=20)),
                ('has_new_shop', models.CharField(blank=True, max_length=30, null=True)),
                ('asset_type', models.CharField(blank=True, max_length=30, null=True)),
                ('has_cylinder', models.CharField(blank=True, max_length=30, null=True)),
                ('cylinder_size', models.CharField(blank=True, max_length=30, null=True)),
                ('cylinder_position', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ('business_name',),
            },
            bases=('accounts.user',),
        ),
    ]
