# Generated by Django 3.2 on 2023-03-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_smeuser2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smeuser2',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='smeuser2',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='SMEUser',
        ),
    ]
