# Generated by Django 3.2 on 2023-03-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20230308_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='business_type',
            new_name='user_class',
        ),
        migrations.RemoveField(
            model_name='smeuser2',
            name='which_user',
        ),
        migrations.AddField(
            model_name='smeuser2',
            name='business_type',
            field=models.CharField(blank=True, default='Business Pro', max_length=30, null=True),
        ),
    ]
