# Generated by Django 3.2 on 2023-03-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_date_of_onboarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_onboarding',
            field=models.DateField(null=True),
        ),
    ]
