# Generated by Django 3.2 on 2023-03-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_date_of_onboarding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_of_onboarding',
            new_name='when_to_onboard',
        ),
    ]
