# Generated by Django 3.2 on 2023-03-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_date_of_onboarding_user_when_to_onboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_onboarding',
            field=models.DateField(auto_now=True),
        ),
    ]
