# Generated by Django 3.2 on 2023-03-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_date_of_onboarding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_of_onboarding',
            new_name='date_for_your_onboarding',
        ),
    ]
