# Generated by Django 4.1.7 on 2023-05-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_user_any_referral_code_user_referred_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user", old_name="when_to_onboard", new_name="date_to_onboard",
        ),
    ]
