# Generated by Django 4.1.7 on 2023-05-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_alter_user_date_for_your_onboarding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_class",
            field=models.CharField(
                blank=True, default="Residential Customers", max_length=30, null=True
            ),
        ),
    ]
