# Generated by Django 4.1.7 on 2023-05-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_alter_user_user_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription_status",
            field=models.BooleanField(default=False),
        ),
    ]
