# Generated by Django 4.1.7 on 2023-06-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_user_subscription_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="lga",
            field=models.CharField(
                choices=[
                    ("Agege", "Agege"),
                    ("Ajeromi-Ifelodun", "Ajeromi-Ifelodun"),
                    ("Alimosho", "Alimosho"),
                    ("Apapa", "Apapa"),
                    ("Amuwo-Odofin", "Amuwo-Odofin"),
                    ("Badagry", "Badagry"),
                    ("Epe", "Epe"),
                    ("Eti-Osa", "Eti-Osa"),
                    ("Ibeju-Lekki", "Ibeju-Lekki"),
                    ("Ifako-Ijaiye", "Ifako-Ijaiye"),
                    ("Ikeja", "Ikeja"),
                    ("Ikorodu", "Ikorodu"),
                    ("Kosofe", "Kosofe"),
                    ("Lagos Island", "Lagos Island"),
                    ("Lagos Mainland", "Lagos Mainland"),
                    ("Mushin", "Mushin"),
                    ("Ojo", "Ojo"),
                    ("Oshodi-Isolo", "Oshodi-Isolo"),
                    ("Somolu", "Somolu"),
                    ("Surulere", "Surulere"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
