# Generated by Django 3.2 on 2023-03-09 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=10, null=True)),
                ('header', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.CharField(max_length=100)),
                ('notif_type', models.CharField(max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SmartBoxMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smart_box', models.CharField(max_length=20)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SmartBoxReadings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('smart_box', models.CharField(max_length=20)),
                ('weight', models.FloatField(max_length=10)),
                ('quantity_supplied', models.FloatField(blank=True, default='0', max_length=10, null=True)),
                ('quantity_used', models.FloatField(blank=True, max_length=10, null=True)),
                ('quantity_remaining', models.FloatField(blank=True, max_length=10, null=True)),
                ('battery_remaining', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cylinder', models.CharField(blank=True, max_length=20, null=True)),
                ('cylinder_tare_weight', models.CharField(blank=True, max_length=20, null=True)),
                ('master', models.CharField(blank=True, default='0', max_length=20, null=True)),
                ('master_battery_level', models.CharField(blank=True, default='0', max_length=20, null=True)),
                ('min_value', models.CharField(blank=True, default='0', max_length=20, null=True)),
                ('max_value', models.CharField(blank=True, default='0', max_length=20, null=True)),
                ('transmit_type', models.CharField(blank=True, choices=[('time', 'time'), ('flow', 'flow')], default='time', max_length=20)),
                ('longitude', models.CharField(blank=True, default='0', max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, default='0', max_length=20, null=True)),
                ('asset_type', models.CharField(default='smart scale', max_length=20)),
                ('last_push', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_push'],
            },
        ),
        migrations.CreateModel(
            name='SmartScaleMonitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smart_scale', models.CharField(max_length=20)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
