# Generated by Django 3.2 on 2023-03-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_readings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartboxreadings',
            name='max_transmit_time',
            field=models.CharField(blank=True, default='25', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='smartboxreadings',
            name='min_transmit_time',
            field=models.CharField(blank=True, default='4', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='smartboxreadings',
            name='asset_type',
            field=models.CharField(default='smart_box', max_length=20),
        ),
    ]
