# Generated by Django 4.1.7 on 2023-05-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meter_readings", "0004_newreading"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestGasReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meter", models.CharField(blank=True, max_length=20, null=True)),
                ("total_quantity_used", models.FloatField(blank=True, null=True)),
                ("quantity_remaining", models.FloatField(blank=True, null=True)),
                (
                    "battery_remaining",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("last_push", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
