# Generated by Django 4.1.7 on 2023-05-23 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meter_readings", "0005_testgasreading"),
    ]

    operations = [
        migrations.RenameField(
            model_name="smartboxreadings",
            old_name="smart_box",
            new_name="smart_box_id",
        ),
    ]
