# Generated by Django 4.1.7 on 2023-05-23 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meter_readings", "0009_collectgasreading_delete_testgasreading"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collectgasreading",
            old_name="total_quantity_used",
            new_name="quantity_used",
        ),
    ]
