# Generated by Django 4.1.7 on 2023-05-23 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0017_alter_gasprice_options_and_more"),
        (
            "meter_readings",
            "0010_rename_total_quantity_used_collectgasreading_quantity_used",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ActivatedReading", new_name="ActivatedSmartBoxReading",
        ),
    ]
