# Generated by Django 4.1.7 on 2023-05-25 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0018_rename_cylinder_type_cylinder_cylinder_capacity_and_more"),
        ("meter_readings", "0011_rename_activatedreading_activatedsmartboxreading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activatedsmartboxreading",
            name="smart_box",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activated_smartbox",
                to="asset.retailassigncylinder",
            ),
        ),
    ]
