# Generated by Django 4.1.7 on 2023-06-01 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0027_rename_retailassigncylinder_residentialassigncylinder"),
        ("meter_readings", "0012_alter_activatedsmartboxreading_smart_box"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectgasreading",
            name="residential_assign_meter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="meter_readings",
                to="asset.residentialassigncylinder",
            ),
        ),
    ]
