# Generated by Django 4.1.7 on 2023-06-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meter_readings", "0014_gasmeterstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="gasmeterstatus",
            name="quantity_supplied",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="gasmeterstatus",
            name="quantity_used",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
