# Generated by Django 4.1.7 on 2023-06-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "meter_readings",
            "0017_gasmeterstatus_user_id_alter_gasmeterstatus_cylinder_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="gasmeterstatus",
            old_name="cylinder",
            new_name="cylinder_serial_number",
        ),
        migrations.RenameField(
            model_name="gasmeterstatus",
            old_name="quantity_remaining",
            new_name="quantity_gas_left",
        ),
    ]
