# Generated by Django 3.2 on 2023-03-09 10:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auxiliary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='must be a valid phone number', regex='^[0]\\d{10}$')])),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_auxiliary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
