# Generated by Django 3.2 on 2023-03-15 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auxilliary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auxiliary',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='auxiliary',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
