# Generated by Django 4.1.7 on 2023-07-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="pin",
            field=models.IntegerField(null=True),
        ),
    ]
