# Generated by Django 3.2 on 2023-03-15 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cylinder_type', models.CharField(blank=True, choices=[('new_cylinder', 'new_cylinder'), ('existing_cylinder', 'existing_cylinder')], max_length=60)),
                ('state', models.CharField(default='Lagos', max_length=60)),
                ('lga', models.CharField(choices=[('Agege', 'Agege'), ('Ajeromi-Ifelodun', 'Ajeromi-Ifelodun'), ('Alimosho', 'Alimosho'), ('Apapa', 'Apapa'), ('Amuwo-Odofin', 'Amuwo-Odofin'), ('Badagry', 'Badagry'), ('Epe', 'Epe'), ('Eti-Osa', 'Eti-Osa'), ('Ibeju-Lekki', 'Ibeju-Lekki'), ('Ifako-Ijaiye', 'Ifako-Ijaiye'), ('Ikeja', 'Ikeja'), ('Ikorodu', 'Ikorodu'), ('Kosofe', 'Kosofe'), ('Lagos Island', 'Lagos Island'), ('Lagos Mainland', 'Lagos Mainland'), ('Mushin', 'Mushin'), ('Ojo', 'Ojo'), ('Oshodi-Isolo', 'Oshodi-Isolo'), ('Somolu', 'Somolu'), ('Surulere', 'Surulere')], max_length=60)),
                ('home_address', models.TextField()),
                ('order_transaction_id', models.CharField(blank=True, max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboard_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
