# Generated by Django 4.1.7 on 2023-06-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_refillorder_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refillorder",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "pending"),
                    ("resheduled", "rescheduled"),
                    ("assigned", "assigned"),
                    ("approved", "approved"),
                    ("ongoing", "ongoing"),
                    ("delivered", "delivered"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
