# Generated by Django 4.1.7 on 2023-06-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_refillorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="refillorder",
            name="access_code",
            field=models.CharField(max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="refillorder",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
