# Generated by Django 4.1.7 on 2023-06-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_refillorder_access_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="refillorder",
            name="order_id",
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
