# Generated by Django 4.1.7 on 2023-06-21 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_rename_ro_deliveryofficer_manager"),
        ("orders", "0007_refillorder_order_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="RefillOrderAssignDeliveryOfficer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_date", models.DateTimeField(auto_now_add=True)),
                (
                    "delivery_officer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_delivery_officer",
                        to="delivery.deliveryofficer",
                    ),
                ),
                (
                    "refill_order",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refill_order",
                        to="orders.refillorder",
                    ),
                ),
            ],
            options={
                "ordering": ("-assigned_date",),
            },
        ),
    ]
