# Generated by Django 4.1.7 on 2023-06-21 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_rename_ro_deliveryofficer_manager"),
        ("orders", "0008_refillorderassigndeliveryofficer"),
    ]

    operations = [
        migrations.AddField(
            model_name="refillorder",
            name="delivery_officer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attached_delivery_officer",
                to="delivery.deliveryofficer",
            ),
        ),
    ]
