# Generated by Django 4.1.7 on 2023-06-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_refillorder_delivery_officer"),
    ]

    operations = [
        migrations.AddField(
            model_name="refillorder",
            name="approved_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="refillorder",
            name="rescheduled_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
