# Generated by Django 4.1.7 on 2023-06-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_refillorder_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refillorder",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accept", "Accept"),
                    ("reschedule", "Reschedule"),
                    ("reject", "Reject"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="refillorder",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "pending"),
                    ("resheduled", "rescheduled"),
                    ("assigned", "assigned"),
                    ("approved", "approved"),
                    ("in progress", "in progress"),
                    ("delivered", "delivered"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
