# Generated by Django 4.1.7 on 2023-06-22 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0027_rename_retailassigncylinder_residentialassigncylinder"),
        ("orders", "0013_alter_refillorder_action_alter_refillorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="refillorder",
            name="new_cylinder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="delivery_new_cylinder",
                to="asset.cylinder",
            ),
        ),
        migrations.AddField(
            model_name="refillorder",
            name="old_cylinder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_low_cylinder",
                to="asset.cylinder",
            ),
        ),
    ]
