# Generated by Django 4.1.7 on 2023-07-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_refillorder_new_cylinder_refillorder_old_cylinder"),
    ]

    operations = [
        migrations.AddField(
            model_name="refillorder",
            name="cylinder_total_weight",
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
