# Generated by Django 4.1.7 on 2023-07-24 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0015_refillorder_cylinder_total_weight"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_id", models.CharField(max_length=20, unique=True)),
                (
                    "invoice_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "billable_assets_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "invoice_status",
                    models.CharField(
                        choices=[("paid", "paid"), ("unpaid", "unpaid")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "refill_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.refillorder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_created"],
            },
        ),
    ]
